name: graphql_schema3
version: 3.2.2
description: >-
  An implementation of the GraphQL type system in Dart. Builds object, union,
  enum, input and scalar types, and validates and coerces values against them.
homepage: https://comapps.web.app/#graphql_schema3
repository: https://github.com/raphrmx/graphql_schema3
issue_tracker: https://github.com/raphrmx/graphql_schema3/issues

topics:
  - graphql
  - schema
  - types

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  source_span: ^1.10.2

dev_dependencies:
  lints: ^6.1.0
  test: ^1.31.0
